@startuml
'https://plantuml.com/class-diagram

package application {

    class AppLaunch {
        + void start()
    }

    class AppData {
        - {static} String language;
        - {static} int prefWidth;
        - {static} int prefHeight;
        - {static} int wonderLayoutSize;
    }

}

package controllers {

    class AlexandrieActionController {

    }

    class AppLauncherController {

    }

    class GameInitController {

    }

    class GameSceneController {

    }

    class HalicarnasseController {

    }

    class LauncherController {

    }

    class PreviewController {

    }

    class ResultsController {
        + void showResults()
    }

    class RulesController {
        + void showRules()
    }

}

package data {

    class Board {

    }

    enum Cards {
            MAT_WOOD
            MAT_GLASS
            MAT_BRICK
            MAT_STONE
            MAT_PAPYRUS
            MAT_GOLD
            LAU_EMPEROR
            LAU_CAT
            SCI_ARCHITECT
            SCI_LAW
            SCI_MECHANIC
            COM_CENTURION
            COM_BARBARIAN
            COM_ARCHER

            object Cards
            - String name
            - String type
            - String front
            - String back
    }

    class Data {

    }

    class Deck {
            - ArrayList<Cards> cards
            + shuffle()
            + draw()
            + removeCard(int index)
    }

    class GameData {

    }

    class Initializers{

    }

    class Player {
        - String playerName
        - Wonder wonder

        - ArrayList<ShieldToken> shieldTokens
        - ArrayList<ProgressToken> progressTokens
        - ArrayList<LaurelToken> laurelTokens
        - ArrayList<MaterialToken> materials

        - boolean hasCat
    }

    class ProgressTokenStack {

    }

    class Wonder {
        - String wonderName
        - int wonderLevel

        - boolean[] sameMaterials
        - int[] nbMaterials

        - int[] levelPoints
        - boolean[] levelAction
    }

}

package mainClasses {

    class Game {

    }

    class test {

    }

    class test2 {

    }

}



package other {

    class LoadScene {

    }

    class UICommonMethods {

    }

    class ModelCommonMethods {
        + nextTurn()
        + drawLeftDeck()
        + drawMiddleDeck()
        + drawRightDeck()
        + drawProgressToken()
    }

}

package token {

    class Fighter {

    }

    class ShieldToken {
            - boolean hasHorn
            - int nbShields
        }

        class LaurelToken {
            - int points
            - int color
        }

        class ProgressToken {
            - String name
        }

        class MaterialToken {
            - String type
            - int color
        }

        class ScienceToken {

        }

        class ShieldToken {

        }

}

GameData o-- Player
GameData o-- Deck
Deck o-- Cards
Player *-- Wonder
Player o-- MaterialToken
Player o-- ShieldToken
Player o-- LaurelToken
Player o-- ProgressToken


@enduml